Add support for CLI namespace set.
paraglider-project/paraglider pull request #352
Opened 2024-05-30 13:42 UTC by aviweit

Currently, Paraglider namespaces are not being supported from the CLI (only 'default' can be used).

It seems that `glide namespace set` has no effect since it sets a local variable in the client itself which is stateless.

In this PR, `glide namespace set` updates the active namespace in the controller side and other CLIs query first the namespace from there and use it to create the resource and rule.

It seems to work well in my local environment. I can create resources in multiple namespaces which results in the creation of multiple VPCs.

The PR is not fully completed: few tests and lint fails.

Can you please review it?

Thanks.

2024-05-30 13:43 UTC, aviweit commented on pkg/orchestrator/orchestrator.go
> +	s.namespace = namespace
Should the active namespace be persisted?

2024-05-30 18:46 UTC, praveingk requested changes
@aviweit Thanks for checking this, and working on it. I am skeptical about maintaining an active namespace in the orchestrator, especially when the orchestrator works across namespace with multiple clients resulting in race conditions. This is the reason, all resource ID have a namespace component. Ideally, the cliSettings could be persisted in the client side (e.g. by json marshaling cliSettings to a file), rather than being propagating it to the orchestrator to keep it simple, and each client independent. @smcclure20 @seankimkdy Let me know what you think.

2024-06-04 11:26 UTC, aviweit commented
Thanks for clarifying this. I am closing this PR.

2024-06-04 11:26 UTC, closed without merging

2024-06-04 18:47 UTC, praveingk commented
@aviweit : Will you be opening another PR with persistency support for namespace in cliSettings? 
cc : @smcclure20