[Docs] Add TSC to repo
paraglider-project/paraglider pull request #370
Opened 2024-06-06 19:05 UTC by smcclure20

This is a requirement from the LFN for candidate projects

2024-06-06 19:26 UTC, divega approved these changes

2024-06-06 20:46 UTC, praveingk approved these changes

2024-06-07 01:06 UTC, seankimkdy requested changes

2024-06-07 01:06 UTC, seankimkdy commented on GOVERNANCE.md
> +Databricks
```suggestion
UC Berkeley
```

I'm with Berkeley until 1st week of August, so I'll change once I start at Databricks.

2024-06-07 18:35 UTC, divega approved these changes

2024-06-08 00:04 UTC, seankimkdy approved these changes

2024-06-08 00:04 UTC, merged