[Azure] Add NAT gateways for outbound public IP addresses
paraglider-project/paraglider pull request #441
Opened 2024-07-22 03:55 UTC by seankimkdy

Takes on Azure portion of #434. This allows resources to have outbound permit list rules with public IP addresses. When a permit list rule with a public IP address target is passed in to `AddPermitListRules`, a NAT gateway is spun up in the vnet where the resource resides. Similar to VPN gateways, the NAT gateway is created on demand and not before it is necessary.

I also refactored Azure's connectivity check methods such that it's more user friendly to those from other clouds.

GCP PR is coming soon after #417 is merged due to a lot of code overlap.

2024-07-24 18:54 UTC, smcclure20 requested changes
Just a couple nits! Thanks!

2024-07-24 18:54 UTC, smcclure20 commented on pkg/azure/plugin.go
> +				natGatewayLocation := *resourceVnet.Location
Nit: Maybe this should be its own function?

2024-07-24 18:54 UTC, smcclure20 commented on pkg/azure/test_utils.go
> +	// Note that external ICMP
Unfinished comment?

2024-07-25 04:16 UTC, seankimkdy commented on pkg/azure/test_utils.go
> +	// Note that external ICMP
Good catch!

2024-07-26 23:19 UTC, smcclure20 approved these changes

2024-07-27 00:52 UTC, merged