[IBM]Support private endpoints
paraglider-project/paraglider pull request #451
Opened 2024-07-26 20:52 UTC by praveingk

2024-08-01 22:05 UTC, smcclure20 requested changes
Thanks for this! Mostly just some nits. 

Also noting that once this is in, we should include some documentation on what the payload should exactly look like for requests.

2024-08-01 22:05 UTC, smcclure20 commented on pkg/ibm/resource.go
> +// CreateResource create an instance
Typo: instance --> private endpoint

2024-08-01 22:05 UTC, smcclure20 commented on pkg/ibm/resource.go
> +	// look for cluster with the specified CRN in the specified namespace.
typo: cluster --> private endpoint

2024-08-01 22:05 UTC, smcclure20 commented on pkg/ibm/resource.go
> +	// add cluster's CRN and region to search attributes
typo: cluster --> private endpoint

2024-08-01 22:05 UTC, smcclure20 commented on pkg/ibm/resource.go
> +	clusterCRN, err := e.getCRN()
cluster or private endpoint? (or something similar)

2024-08-01 22:13 UTC, praveingk commented on pkg/ibm/plugin_test.go
> +				} else {
Agree. Will change to have a dependency with creation of subnet, which is common for cluster and vpe.

2024-08-16 01:26 UTC, smcclure20 approved these changes

2024-08-16 16:31 UTC, merged